
package com.servientrega;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsRastreoEnvios", targetNamespace = "http://servientrega.com/", wsdlLocation = "http://sismilenio.servientrega.com/wsrastreoenvios/wsRastreoEnvios.asmx?wsdl")
public class WsRastreoEnvios
    extends Service
{

    private final static URL WSRASTREOENVIOS_WSDL_LOCATION;
    private final static WebServiceException WSRASTREOENVIOS_EXCEPTION;
    private final static QName WSRASTREOENVIOS_QNAME = new QName("http://servientrega.com/", "wsRastreoEnvios");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sismilenio.servientrega.com/wsrastreoenvios/wsRastreoEnvios.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSRASTREOENVIOS_WSDL_LOCATION = url;
        WSRASTREOENVIOS_EXCEPTION = e;
    }

    public WsRastreoEnvios() {
        super(__getWsdlLocation(), WSRASTREOENVIOS_QNAME);
    }

    public WsRastreoEnvios(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSRASTREOENVIOS_QNAME, features);
    }

    public WsRastreoEnvios(URL wsdlLocation) {
        super(wsdlLocation, WSRASTREOENVIOS_QNAME);
    }

    public WsRastreoEnvios(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSRASTREOENVIOS_QNAME, features);
    }

    public WsRastreoEnvios(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRastreoEnvios(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsRastreoEnviosSoap
     */
    @WebEndpoint(name = "wsRastreoEnviosSoap")
    public WsRastreoEnviosSoap getWsRastreoEnviosSoap() {
        return super.getPort(new QName("http://servientrega.com/", "wsRastreoEnviosSoap"), WsRastreoEnviosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRastreoEnviosSoap
     */
    @WebEndpoint(name = "wsRastreoEnviosSoap")
    public WsRastreoEnviosSoap getWsRastreoEnviosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://servientrega.com/", "wsRastreoEnviosSoap"), WsRastreoEnviosSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSRASTREOENVIOS_EXCEPTION!= null) {
            throw WSRASTREOENVIOS_EXCEPTION;
        }
        return WSRASTREOENVIOS_WSDL_LOCATION;
    }

}
