
package com.servientrega;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsRastreoEnviosSoap", targetNamespace = "http://servientrega.com/")
@XmlSeeAlso({
    com.servientrega.ObjectFactory.class,
    org.w3._2001.xmlschema.ObjectFactory.class
})
public interface WsRastreoEnviosSoap {


    /**
     * Operación que permite consultar por número de identificación del cliente y número de guía, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento relacionado que ingreso el cliente al momento de crear la guía, este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param guia
     * @return
     *     returns com.servientrega.EstadoGuiaResponse.EstadoGuiaResult
     */
    @WebMethod(operationName = "EstadoGuia", action = "http://servientrega.com/EstadoGuia")
    @WebResult(name = "EstadoGuiaResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuia", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuia")
    @ResponseWrapper(localName = "EstadoGuiaResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiaResponse")
    public com.servientrega.EstadoGuiaResponse.EstadoGuiaResult estadoGuia(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "guia", targetNamespace = "http://servientrega.com/")
        String guia);

    /**
     * Operación que permite consultar por fecha de entrega del envío, número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llega a aplicar e imagen de la prueba de entrega entre otros.
     * 
     * @param fecha
     * @param idCliente
     * @param idContacto
     * @param pwd
     * @return
     *     returns com.servientrega.ArrayOfInfEnvios
     */
    @WebMethod(operationName = "ConsultarGestionEntregas", action = "http://servientrega.com/ConsultarGestionEntregas")
    @WebResult(name = "ConsultarGestionEntregasResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionEntregas", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionEntregas")
    @ResponseWrapper(localName = "ConsultarGestionEntregasResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionEntregasResponse")
    public ArrayOfInfEnvios consultarGestionEntregas(
        @WebParam(name = "Fecha", targetNamespace = "http://servientrega.com/")
        String fecha,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar por número de identificación del cliente y el número de documento que hace referencia al número de factura, pedido, o identificador único que relacionó el cliente al momento de crear la guía, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento  relacionado  que ingreso el cliente al momento de crear la guía este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param relacionDocumentos
     * @return
     *     returns com.servientrega.EstadoGuiasIdDocumentoClienteResponse.EstadoGuiasIdDocumentoClienteResult
     */
    @WebMethod(operationName = "EstadoGuiasIdDocumentoCliente", action = "http://servientrega.com/EstadoGuiasIdDocumentoCliente")
    @WebResult(name = "EstadoGuiasIdDocumentoClienteResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuiasIdDocumentoCliente", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasIdDocumentoCliente")
    @ResponseWrapper(localName = "EstadoGuiasIdDocumentoClienteResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasIdDocumentoClienteResponse")
    public com.servientrega.EstadoGuiasIdDocumentoClienteResponse.EstadoGuiasIdDocumentoClienteResult estadoGuiasIdDocumentoCliente(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "RelacionDocumentos", targetNamespace = "http://servientrega.com/")
        String relacionDocumentos);

    /**
     * Operación que permite consultar por número de guía, número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llegar a aplicar e imagen de la prueba de entrega entre otros.
     * 
     * @param idCliente
     * @param idContacto
     * @param pwd
     * @param sGuia
     * @return
     *     returns com.servientrega.ArrayOfInfEnvios
     */
    @WebMethod(operationName = "ConsultarGestionGuias", action = "http://servientrega.com/ConsultarGestionGuias")
    @WebResult(name = "ConsultarGestionGuiasResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionGuias", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionGuias")
    @ResponseWrapper(localName = "ConsultarGestionGuiasResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionGuiasResponse")
    public ArrayOfInfEnvios consultarGestionGuias(
        @WebParam(name = "sGuia", targetNamespace = "http://servientrega.com/")
        String sGuia,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar detalladamente la información de la guía tales como: información del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar  a su destino o ser devuelto al remitente y la imagen de la prueba de entrega digitalizada. 
     * 
     * @param numeroGuia
     * @return
     *     returns com.servientrega.InformacionGuiaMov
     */
    @WebMethod(operationName = "ConsultarGuia", action = "http://servientrega.com/ConsultarGuia")
    @WebResult(name = "ConsultarGuiaResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuia", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuia")
    @ResponseWrapper(localName = "ConsultarGuiaResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaResponse")
    public InformacionGuiaMov consultarGuia(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia);

    /**
     * Operación que permite consultar detalladamente la información de la guía tales como: información del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar  a su destino o ser devuelto al remitente. Este método permite indicar si desea buscar o no la imagen digitalizada de la prueba de entrega.
     * 
     * @param numeroGuia
     * @param buscarImagen
     * @return
     *     returns com.servientrega.InformacionGuiaMov
     */
    @WebMethod(operationName = "ConsultarGuiaImagen", action = "http://servientrega.com/ConsultarGuiaImagen")
    @WebResult(name = "ConsultarGuiaImagenResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaImagen", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagen")
    @ResponseWrapper(localName = "ConsultarGuiaImagenResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagenResponse")
    public InformacionGuiaMov consultarGuiaImagen(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia,
        @WebParam(name = "BuscarImagen", targetNamespace = "http://servientrega.com/")
        boolean buscarImagen);

    /**
     * Operación que permite consultar detalladamente la información para cleinte externo: información del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar  a su destino o ser devuelto al remitente y la imagen de la prueba de entrega digitalizada. 
     * 
     * @param numeroGuia
     * @return
     *     returns com.servientrega.InformacionGuiaMov
     */
    @WebMethod(operationName = "ConsultarGuiaExterno", action = "http://servientrega.com/ConsultarGuiaExterno")
    @WebResult(name = "ConsultarGuiaExternoResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaExterno", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaExterno")
    @ResponseWrapper(localName = "ConsultarGuiaExternoResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaExternoResponse")
    public InformacionGuiaMov consultarGuiaExterno(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia);

    /**
     * Operación que permite consultar por número de identificación del cliente y un bloque de números de guías, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento relacionado que ingreso el cliente al momento de crear la guía este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param relacionGuias
     * @return
     *     returns com.servientrega.EstadoGuiasResponse.EstadoGuiasResult
     */
    @WebMethod(operationName = "EstadoGuias", action = "http://servientrega.com/EstadoGuias")
    @WebResult(name = "EstadoGuiasResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuias", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuias")
    @ResponseWrapper(localName = "EstadoGuiasResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasResponse")
    public com.servientrega.EstadoGuiasResponse.EstadoGuiasResult estadoGuias(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "RelacionGuias", targetNamespace = "http://servientrega.com/")
        String relacionGuias);

    /**
     * Operación que permite consultar por fecha de entrega número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de las devoluciones que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llegar a aplicar e imagen de la guía donde se evidencia dicha gestión.
     * 
     * @param fecha
     * @param idCliente
     * @param idContacto
     * @param pwd
     * @return
     *     returns com.servientrega.ArrayOfInfEnvios
     */
    @WebMethod(operationName = "ConsultarGestionDevoluciones", action = "http://servientrega.com/ConsultarGestionDevoluciones")
    @WebResult(name = "ConsultarGestionDevolucionesResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionDevoluciones", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionDevoluciones")
    @ResponseWrapper(localName = "ConsultarGestionDevolucionesResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionDevolucionesResponse")
    public ArrayOfInfEnvios consultarGestionDevoluciones(
        @WebParam(name = "Fecha", targetNamespace = "http://servientrega.com/")
        String fecha,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar la imagen de la prueba de entrega digitalizada por número de guía.
     * 
     * @param strGuia
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "ImagenGuia", action = "http://servientrega.com/ImagenGuia")
    @WebResult(name = "ImagenGuiaResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ImagenGuia", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ImagenGuia")
    @ResponseWrapper(localName = "ImagenGuiaResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ImagenGuiaResponse")
    public byte[] imagenGuia(
        @WebParam(name = "strGuia", targetNamespace = "http://servientrega.com/")
        String strGuia);

    /**
     * Operación que permite consultar detalladamente la información de la guía de acuerdo con el nùmero de referencia del cliente.
     * 
     * @param idCliente
     * @param numeroReferencia
     * @return
     *     returns com.servientrega.InformacionGuiaMov
     */
    @WebMethod(operationName = "ConsultarGuiaPorNumeroReferenciaCliente", action = "http://servientrega.com/ConsultarGuiaPorNumeroReferenciaCliente")
    @WebResult(name = "ConsultarGuiaPorNumeroReferenciaClienteResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaPorNumeroReferenciaCliente", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaPorNumeroReferenciaCliente")
    @ResponseWrapper(localName = "ConsultarGuiaPorNumeroReferenciaClienteResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaPorNumeroReferenciaClienteResponse")
    public InformacionGuiaMov consultarGuiaPorNumeroReferenciaCliente(
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Numero_Referencia", targetNamespace = "http://servientrega.com/")
        String numeroReferencia);

    /**
     * Operación que permite consultar la foto y/o la firma y/o foto de la guía de la novedad a la entrega o devolución del envio
     * 
     * @param numeroGuia
     * @param idProceso
     * @return
     *     returns com.servientrega.ConsultarGuiaImagenNovedadesXMLResponse.ConsultarGuiaImagenNovedadesXMLResult
     */
    @WebMethod(operationName = "ConsultarGuiaImagenNovedadesXML", action = "http://servientrega.com/ConsultarGuiaImagenNovedadesXML")
    @WebResult(name = "ConsultarGuiaImagenNovedadesXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaImagenNovedadesXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagenNovedadesXML")
    @ResponseWrapper(localName = "ConsultarGuiaImagenNovedadesXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagenNovedadesXMLResponse")
    public com.servientrega.ConsultarGuiaImagenNovedadesXMLResponse.ConsultarGuiaImagenNovedadesXMLResult consultarGuiaImagenNovedadesXML(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia,
        @WebParam(name = "IdProceso", targetNamespace = "http://servientrega.com/")
        int idProceso);

    /**
     * Operación que permite consultar por número de identificación del cliente y número de guía, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento relacionado que ingresò el cliente al momento de crear la guía, este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param guia
     * @return
     *     returns com.servientrega.EstadoGuiaXMLResponse.EstadoGuiaXMLResult
     */
    @WebMethod(operationName = "EstadoGuiaXML", action = "http://servientrega.com/EstadoGuiaXML")
    @WebResult(name = "EstadoGuiaXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuiaXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiaXML")
    @ResponseWrapper(localName = "EstadoGuiaXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiaXMLResponse")
    public com.servientrega.EstadoGuiaXMLResponse.EstadoGuiaXMLResult estadoGuiaXML(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "guia", targetNamespace = "http://servientrega.com/")
        String guia);

    /**
     * Operación que permite consultar por fecha de entrega del envío, número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llega a aplicar e imagen de la prueba de entrega entre otros.
     * 
     * @param fecha
     * @param idCliente
     * @param idContacto
     * @param pwd
     * @return
     *     returns com.servientrega.ConsultarGestionEntregasXMLResponse.ConsultarGestionEntregasXMLResult
     */
    @WebMethod(operationName = "ConsultarGestionEntregasXML", action = "http://servientrega.com/ConsultarGestionEntregasXML")
    @WebResult(name = "ConsultarGestionEntregasXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionEntregasXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionEntregasXML")
    @ResponseWrapper(localName = "ConsultarGestionEntregasXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionEntregasXMLResponse")
    public com.servientrega.ConsultarGestionEntregasXMLResponse.ConsultarGestionEntregasXMLResult consultarGestionEntregasXML(
        @WebParam(name = "Fecha", targetNamespace = "http://servientrega.com/")
        String fecha,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar por número de identificación del cliente y el número de documento que hace referencia al número de factura, pedido, o identificador único que relacionó el cliente al momento de crear la guía, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento  relacionado  que ingreso el cliente al momento de crear la guía este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param relacionDocumentos
     * @return
     *     returns com.servientrega.EstadoGuiasIdDocumentoClienteXMLResponse.EstadoGuiasIdDocumentoClienteXMLResult
     */
    @WebMethod(operationName = "EstadoGuiasIdDocumentoClienteXML", action = "http://servientrega.com/EstadoGuiasIdDocumentoClienteXML")
    @WebResult(name = "EstadoGuiasIdDocumentoClienteXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuiasIdDocumentoClienteXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasIdDocumentoClienteXML")
    @ResponseWrapper(localName = "EstadoGuiasIdDocumentoClienteXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasIdDocumentoClienteXMLResponse")
    public com.servientrega.EstadoGuiasIdDocumentoClienteXMLResponse.EstadoGuiasIdDocumentoClienteXMLResult estadoGuiasIdDocumentoClienteXML(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "RelacionDocumentos", targetNamespace = "http://servientrega.com/")
        String relacionDocumentos);

    /**
     * Operación que permite consultar por número de guía, número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llegar a aplicar e imagen de la prueba de entrega entre otros.
     * 
     * @param idCliente
     * @param guia
     * @param idContacto
     * @param pwd
     * @return
     *     returns com.servientrega.ConsultarGestionGuiasXMLResponse.ConsultarGestionGuiasXMLResult
     */
    @WebMethod(operationName = "ConsultarGestionGuiasXML", action = "http://servientrega.com/ConsultarGestionGuiasXML")
    @WebResult(name = "ConsultarGestionGuiasXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionGuiasXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionGuiasXML")
    @ResponseWrapper(localName = "ConsultarGestionGuiasXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionGuiasXMLResponse")
    public com.servientrega.ConsultarGestionGuiasXMLResponse.ConsultarGestionGuiasXMLResult consultarGestionGuiasXML(
        @WebParam(name = "Guia", targetNamespace = "http://servientrega.com/")
        String guia,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar detalladamente la información de la guía tales como: información del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar  a su destino o ser devuelto al remitente y la imagen de la prueba de entrega digitalizada. 
     * 
     * @param numeroGuia
     * @return
     *     returns com.servientrega.ConsultarGuiaXMLResponse.ConsultarGuiaXMLResult
     */
    @WebMethod(operationName = "ConsultarGuiaXML", action = "http://servientrega.com/ConsultarGuiaXML")
    @WebResult(name = "ConsultarGuiaXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaXML")
    @ResponseWrapper(localName = "ConsultarGuiaXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaXMLResponse")
    public com.servientrega.ConsultarGuiaXMLResponse.ConsultarGuiaXMLResult consultarGuiaXML(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia);

    /**
     * Operación que permite consultar detalladamente la información de la guía tales como: información del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar  a su destino o ser devuelto al remitente. Este método permite indicar si desea buscar o no la imagen digitalizada de la prueba de entrega.
     * 
     * @param numeroGuia
     * @param buscarImagen
     * @return
     *     returns com.servientrega.ConsultarGuiaImagenXMLResponse.ConsultarGuiaImagenXMLResult
     */
    @WebMethod(operationName = "ConsultarGuiaImagenXML", action = "http://servientrega.com/ConsultarGuiaImagenXML")
    @WebResult(name = "ConsultarGuiaImagenXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaImagenXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagenXML")
    @ResponseWrapper(localName = "ConsultarGuiaImagenXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaImagenXMLResponse")
    public com.servientrega.ConsultarGuiaImagenXMLResponse.ConsultarGuiaImagenXMLResult consultarGuiaImagenXML(
        @WebParam(name = "NumeroGuia", targetNamespace = "http://servientrega.com/")
        String numeroGuia,
        @WebParam(name = "BuscarImagen", targetNamespace = "http://servientrega.com/")
        String buscarImagen);

    /**
     * Operación que permite consultar por número de identificación del cliente y un bloque de números de guías, la gestión de entrega que tuvo el envío permitiendo conocer el estado del envío, motivo de la última devolución si llega a aplicar y el número de documento relacionado que ingreso el cliente al momento de crear la guía este campo puede contener número de pedido, factura, etc.
     * 
     * @param idCliente
     * @param relacionGuias
     * @return
     *     returns com.servientrega.EstadoGuiasXMLResponse.EstadoGuiasXMLResult
     */
    @WebMethod(operationName = "EstadoGuiasXML", action = "http://servientrega.com/EstadoGuiasXML")
    @WebResult(name = "EstadoGuiasXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "EstadoGuiasXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasXML")
    @ResponseWrapper(localName = "EstadoGuiasXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.EstadoGuiasXMLResponse")
    public com.servientrega.EstadoGuiasXMLResponse.EstadoGuiasXMLResult estadoGuiasXML(
        @WebParam(name = "ID_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "RelacionGuias", targetNamespace = "http://servientrega.com/")
        String relacionGuias);

    /**
     * Operación que permite consultar por fecha de entrega número de identificación del cliente, número de identificación del contacto y password del contacto asignado por servientrega y que luego es cambiado por el contacto, la gestión de las devoluciones que tuvo el envío permitiendo conocer el estado del envío, motivo de devolución si llegar a aplicar e imagen de la guía donde se evidencia dicha gestión.
     * 
     * @param fecha
     * @param idCliente
     * @param idContacto
     * @param pwd
     * @return
     *     returns com.servientrega.ConsultarGestionDevolucionesXMLResponse.ConsultarGestionDevolucionesXMLResult
     */
    @WebMethod(operationName = "ConsultarGestionDevolucionesXML", action = "http://servientrega.com/ConsultarGestionDevolucionesXML")
    @WebResult(name = "ConsultarGestionDevolucionesXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGestionDevolucionesXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionDevolucionesXML")
    @ResponseWrapper(localName = "ConsultarGestionDevolucionesXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGestionDevolucionesXMLResponse")
    public com.servientrega.ConsultarGestionDevolucionesXMLResponse.ConsultarGestionDevolucionesXMLResult consultarGestionDevolucionesXML(
        @WebParam(name = "Fecha", targetNamespace = "http://servientrega.com/")
        String fecha,
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd);

    /**
     * Operación que permite consultar detalladamente la información de la guía de acuerdo con el nùmero de referencia del cliente.
     * 
     * @param idCliente
     * @param numeroReferencia
     * @return
     *     returns com.servientrega.ConsultarGuiaPorNumeroReferenciaClienteXMLResponse.ConsultarGuiaPorNumeroReferenciaClienteXMLResult
     */
    @WebMethod(operationName = "ConsultarGuiaPorNumeroReferenciaClienteXML", action = "http://servientrega.com/ConsultarGuiaPorNumeroReferenciaClienteXML")
    @WebResult(name = "ConsultarGuiaPorNumeroReferenciaClienteXMLResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarGuiaPorNumeroReferenciaClienteXML", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaPorNumeroReferenciaClienteXML")
    @ResponseWrapper(localName = "ConsultarGuiaPorNumeroReferenciaClienteXMLResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarGuiaPorNumeroReferenciaClienteXMLResponse")
    public com.servientrega.ConsultarGuiaPorNumeroReferenciaClienteXMLResponse.ConsultarGuiaPorNumeroReferenciaClienteXMLResult consultarGuiaPorNumeroReferenciaClienteXML(
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Numero_Referencia", targetNamespace = "http://servientrega.com/")
        String numeroReferencia);

    /**
     * Operación que permite consultar informacion detallada de más de una guía separadas por coma. Este metodo de operacion permite al cliente obtener el siguiente tipo de informacion: datos del remitente, destinatario y No. CUN PQR (Peticiones quejas y reclamos), documento relacionado del cliente que es un identificador único del cliente puede ser un numero de pedido, factura, etc., placa del vehículo que transporto el envío, así como también todos los movimientos logísticos que tuvo la guía para llegar a su destino o ser devuelto al remitente y la imagen de la prueba de entrega digitalizada.
     * 
     * @param numerosGuias
     * @return
     *     returns com.servientrega.ConsultarInfoGuiasResponse.ConsultarInfoGuiasResult
     */
    @WebMethod(operationName = "ConsultarInfoGuias", action = "http://servientrega.com/ConsultarInfoGuias")
    @WebResult(name = "ConsultarInfoGuiasResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultarInfoGuias", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarInfoGuias")
    @ResponseWrapper(localName = "ConsultarInfoGuiasResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultarInfoGuiasResponse")
    public com.servientrega.ConsultarInfoGuiasResponse.ConsultarInfoGuiasResult consultarInfoGuias(
        @WebParam(name = "NumerosGuias", targetNamespace = "http://servientrega.com/")
        String numerosGuias);

    /**
     * Operación que permite consultar la información de todos los envíos que se encuentren en estado entregado y entregado remitente de un cliente corporativo donde la generación se realizó de la plataforma de Sisclinet, teniendo en cuenta el número de identificación del cliente, número de identificación del contacto del cliente, contraseña del contacto, fecha inicial y la final de entrega del envío.
     * 
     * @param fechaInicial
     * @param idCliente
     * @param idContacto
     * @param fechaFinal
     * @param pwd
     * @return
     *     returns com.servientrega.ConsultaGuiasGestionEntregaClienteResponse.ConsultaGuiasGestionEntregaClienteResult
     */
    @WebMethod(operationName = "ConsultaGuiasGestionEntregaCliente", action = "http://servientrega.com/ConsultaGuiasGestionEntregaCliente")
    @WebResult(name = "ConsultaGuiasGestionEntregaClienteResult", targetNamespace = "http://servientrega.com/")
    @RequestWrapper(localName = "ConsultaGuiasGestionEntregaCliente", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultaGuiasGestionEntregaCliente")
    @ResponseWrapper(localName = "ConsultaGuiasGestionEntregaClienteResponse", targetNamespace = "http://servientrega.com/", className = "com.servientrega.ConsultaGuiasGestionEntregaClienteResponse")
    public com.servientrega.ConsultaGuiasGestionEntregaClienteResponse.ConsultaGuiasGestionEntregaClienteResult consultaGuiasGestionEntregaCliente(
        @WebParam(name = "Id_Cliente", targetNamespace = "http://servientrega.com/")
        String idCliente,
        @WebParam(name = "Id_Contacto", targetNamespace = "http://servientrega.com/")
        String idContacto,
        @WebParam(name = "Pwd", targetNamespace = "http://servientrega.com/")
        String pwd,
        @WebParam(name = "FechaInicial", targetNamespace = "http://servientrega.com/")
        String fechaInicial,
        @WebParam(name = "FechaFinal", targetNamespace = "http://servientrega.com/")
        String fechaFinal);

}
